version: '3.5'

services:
  java_vertx:
    build: .
    ports:
      - "8080:8080"

  db_money_system:
    container_name: db_MoneySystem
    image: postgres:15.2-alpine
    restart: always
    ports:
      - "5832:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=db265
      - POSTGRES_USER=postgres
#      - POSTGRES_DATABASE=moneysystemdocker

